### ISSUE TITLE
[SOLVED] Please add support for non-English text.

### ISSUE THREAD

**Issue by shilik** [Remeic/vue-highlighter#7] opened 2018-04-25 01:04 UTC
Hi, Your plugin is amazing.  I have tried it and it worked great.
But I found that when the string is either Chinese or Japanese, nothing happened.
I have tried to add space between words(there is no space in between words in Chinese and Japanese), but in vain. I plan to use this feature for Chinese /Japanese speaking instruction. It would be great when learners can see the colored-feedback of what they have done correctly in real time. 
Please tell me how to deal with this problem. Thank you very much.

Best regards.

Shilik
![works](https://user-images.githubusercontent.com/1404868/39221086-9f7113b0-4867-11e8-88e9-da81f6fa748b.png)
![not-ok](https://user-images.githubusercontent.com/1404868/39221094-a4cbcc2e-4867-11e8-86f2-29edff688cd6.png)

**Comment by Remeic** [comment] 2018-04-25 06:30
Hi @shilik thanks for contributing :heart:, i try to figure It out in the next days

Thanks again

**Comment by shilik** [comment] 2018-04-25 06:42
Hi, Giulio Fagioli,
Thank you very much for the quick reply.
Looking forward to the patches. :)

Best.

shilik



2018-04-25 14:30 GMT+08:00 Giulio Fagioli <notifications@github.com>:

**Comment by astagi** [comment] 2018-04-25 10:11
You sure @shilik ? it works for me!

<img width="342" alt="screen shot 2018-04-25 at 12 14 27" src="https://user-images.githubusercontent.com/537363/39239782-3e7d2678-4882-11e8-9f88-1dbc7fbbaec2.png">

```
<script>
import vueHighlighter from '../src/index'

export default {
  data: ()=>{
    return {
      text: '史密斯是美国人。 史密斯是王明的朋友',
      word: '史密斯是',
      live: true,
      style: {
        color: '#4286f4'
      }
    }
  },
  directive: {
    vueHighlighter
  }
}
</script>
```

**Comment by shilik** [comment] 2018-04-25 12:03
Well, let me elaborate the problem much clearer.
I found that if the input is "exact part of words" in a sentence, it works
as expected.
however, if part of the input is inconsistent with the target string.
The highlight won't work.
Please see the attached pics of the one works and no-works.

Best.

Shilik


2018-04-25 18:11 GMT+08:00 Δndrea Stagi <notifications@github.com>:

**Comment by astagi** [comment] 2018-04-26 13:53
Hey @shilik it's a little bit difficult to reproduce the problem, could you please share the code you use?

Thanks in advance

**Comment by shilik** [comment] 2018-04-26 15:03
Please use vue init vuetifyjs/webpack  to create a new project.
And try the string like 日本語が 日本語の 情報処理も 情報処理は
to see the result.

Best

Shilik

//main.js
import Vue from "vue";
import App from "./App";
import router from "./router";
import Vuetify from "vuetify";
import "vuetify/dist/vuetify.min.css";
import vueHighlighter from "vue-highlighter";

Vue.directive(vueHighlighter);
Vue.use(Vuetify);

Vue.config.productionTip = false;

/* eslint-disable no-new */
new Vue({
el: "#app",
router,
components: { App },
template: "<App/>"
});

//HelloWorld.vue
<template>
<v-container fluid>
<v-slide-y-transition mode="out-in">
<v-layout column align-center>
<blockquote>
<p v-highlight="{word:word, live:live, style:style}"> {{text}} </p>
<footer>
<v-text-field name="name" label="matching" id="id" v-model="word"></
v-text-field>
</footer>
</blockquote>
</v-layout>
</v-slide-y-transition>
</v-container>
</template>

<script>
import vueHighlighter from "vue-highlighter";
export default {
  directives: {
    vueHighlighter
  },
  data() {
    return {
      text: "日本語の情報処理もできますか",
      word: "",
      live: true,
      style: {
        color: "#f44336",
        bgColor: "#eeeeee"
      }
    };
  }
};
</script>


Δndrea Stagi <notifications@github.com> 於 2018年4月26日 週四 下午9:53寫道：

**Comment by Remeic** [comment] 2018-04-26 16:47
Hello @shilik , to get the result you want, you can insert a regexp in the matching field, in this case try to divide the words you want to highlight with ' | '

Example: 
![Example](https://media.giphy.com/media/oFubV3VYhL7qhoWeOK/giphy.gif)

**Comment by shilik** [comment] 2018-04-27 01:01
![20180427_084750_highlighter](https://user-images.githubusercontent.com/1404868/39353561-a6308e86-4a3a-11e8-8473-8a69c4406816.gif)
Hi,Giulio Fagioli

Thanks for the response and suggestion. I have somehow managed to make it
work with the preprocessing of the input string by a php module called
mecab-php. As there is no space between the words in Japanese or Chinese
sentences, so the in-advanced segmentation is necessary. That is, I have to
split the sentence into several pieces first, then add "|" to each piece,
and combine them all together for the string matching.

The attached file shows what I have done so far.
BTW, Is there any way to remove the space of the highlighted sentence?
I have tried regex such as str.replace(/\s/g,' ') without any success.
As I have mentioned above, spaces are unnatural in the Japanese or Chinese
sentences.

Thank you very much.

Best.

Shilik


Giulio Fagioli <notifications@github.com> 於 2018年4月27日 週五 上午12:47寫道：

**Comment by Remeic** [comment] 2018-04-27 08:52
@shilik You want this result? (no horizontal space)
![image](https://user-images.githubusercontent.com/7298302/39353797-0faebdba-4a09-11e8-91ab-dce5e3ab68fd.png)

**Comment by shilik** [comment] 2018-04-27 09:25
Yes, That is exactly what I need. As I mentioned, for non-English languages
such as Japanese and Chinese, there is no space between words.
Therefore, an ideal highlight for me is something like the following:
 日本語の文字のハイライトもやっとできるようになった。
when a word like ハイライト is entered. no extra space, just high-light!
Have you applied any patches?

Best regards,

Shilik

Giulio Fagioli <notifications@github.com> 於 2018年4月27日 週五 下午4:52寫道：

**Comment by Remeic** [comment] 2018-04-27 09:48
@shilik i'm working on a patch that allow to customize the space, anyway i open a new issue to this 'enhancement'

Now refer to this #9 

I close this issue

**Closed as completed** 2018-04-27 09:50 UTC

**Comment by shilik** [comment] 2018-04-27 09:53
Great! Thank you very much for your contribution.

Best,

Shilik

Giulio Fagioli <notifications@github.com> 於 2018年4月27日 週五 下午5:50寫道：
